config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "poissons", to: "poissons#index"
  get "profil", to: "poissons#profil"
  # get "new_poisson", to: "poisson#new_poisson"
  get "poissons/new", to: "poissons#new"
  post "poissons", to: "poissons#create"

  # get "poissons", to: "pages#poissons",      as: :poissons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :poissons do
    resources :locations, only: %i[create new show]
    # member do
    #   patch :favorite, :unfavorite
    # end
  end
  get "users/:id/profile", to: "pages#profile", as: :user_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :poisson
  belongs_to :user
end

app/models/poisson.rb
class Poisson < ApplicationRecord
  belongs_to :user
  has_many :locations
end

app/models/user.rb
class User < ApplicationRecord
  has_many :poissons, dependent: :destroy
  has_many :locations, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include PgSearch::Model
  pg_search_scope :search_by_name_and_category,
    against: [ :name, :category ],
    using: {
      tsearch: { prefix: true }
    }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_location, only: [:show]
  before_action :set_poisson, only: %i[new create]

  def index
    @locations = current_user.locations
  end

  def show
    @location
  end

  def new
    @poisson = Poisson.find(params[:id])
    @location = Location.new
  end

  def edit
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    @location.poisson = Poisson.find(params[:poisson_id])
    if @location.save
      redirect_to poisson_location_path(@location.poisson, @location)
    else
      redirect_to poisson_path(@poisson)
    end
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def set_poisson
    @poisson = Poisson.find(params[:poisson_id])
  end

  def location_params
    params.require(:location).permit(:begin_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @poissons = Poisson.all.first(3)
    @locations = Location.where(user: current_user)
  end
end

app/controllers/poissons_controller.rb
class PoissonsController < ApplicationController
  before_action :set_poisson, only: [:show, :destroy]
  def index
    @poissons = Poisson.all
    if params[:query].present?
      sql_subquery = "name ILIKE :query OR category ILIKE :query"
      @poissons = @poissons.where(sql_subquery, query: "%#{params[:query]}%")
    end

    @users = User.joins(:poissons).where(poissons: { id: @poissons })
    # The `geocoded` scope filters only flats with coordinates
    @markers = @users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude
      }
    end
  end

  def profil
    @poissons = Poisson.select { |poisson| poisson.user == current_user }
  end

  def show
    @location = Location.new
    @disable_date = @poisson.locations.map do |location|
      { from: location.begin_date, to: location.end_date }
    end
    @markers = []
    @markers << { lat: @poisson.user.latitude, lng: @poisson.user.longitude }
  end

  def new
    @poisson = Poisson.new
  end

  def create
    # @poisson = Poisson.new(params[:poisson])
    @poisson = Poisson.new(poisson_params)
    @poisson.user = current_user
    if @poisson.save
      redirect_to poissons_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @poisson = Poisson.find(params[:id])
    @poisson.destroy
    redirect_to poissons_path, status: :see_other
  end

  private

  def set_poisson
    @poisson = Poisson.find(params[:id])
  end

  def poisson_params
    params.require(:poisson).permit(:name, :category, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FISHBNB</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

  </head>

<link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="content" style="min-height: calc(100vh - 140px)">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/locations/_form.html.erb
<div class="confirmation-box">
  <div class="listing-price">
    <div class="form-group">

      <h4>pour <%= @poisson.price %>€ par jour</h4>
      <%= simple_form_for [@poisson, @location], data: { controller: "datepicker", datepicker_disable_value: @disable_date.to_json } do |f| %>
        <%= f.input :begin_date, as: :string, input_html: { data: { datepicker_target: "start" } } %>
        <%= f.input :end_date, as: :string, input_html: { data: { datepicker_target: "end"} } %>
        <%= f.label :party_size %>

        <h5>Sous-total: <strong>€<%= @poisson.price %></strong></h5><br>

        <%= f.submit "Demander une réservation", class: "btn btn-success form-control" %>
        <br><br>
      <% end %>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<h1> mes resa</h1>

app/views/locations/show.html.erb
<div class="thanks-container d-flex justify-content-center align-items-center">
  <div>
    <div class="mb-4 text-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="text-success" width="75" height="75"
            fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
            <path
                d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
        </svg>
    </div>
    <div class="text-center">
        <h1>Merci !</h1>
        <p>Votre demande de réservation concernant <strong><%=  @location.poisson.name %></strong> du <%=  @location.begin_date %> au <%=  @location.end_date %> a bien été enregistrée.</p>
        <button class="btn btn-success"><%= link_to "Voir les autres poissons", poissons_path %></button>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner poisson_btnTarget" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.oobaooba.fr/img/post/21.jpg);">
  <div class="container ">
    <h1 class="home-h1" >La <strong>passion</strong> des <strong>poissons</strong>!</h1>
    <button class="btn poisson_btn mx-auto" type="button">
      <%= link_to "Découvre nos fabuleux poissons à louer !", poissons_path %>
    </button>
  </div>
</div>

<div class="cards">

  <% @poissons.each do |poisson| %>
    <%= link_to poisson_path(poisson), class:"home-a" do %>
      <div class="card grow" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(<%= poisson.picture_url %>)">
        <div class="card-infos">
              <h2 class="home-h2" ><strong><%= poisson.name %></strong></h2>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/poissons.html.erb
<h1> Louez le poisson de vos rêves !</h1>

<ul>
  <% @poissons.each do |poisson| %>
    <div class="card-product">
      <img src="https://images.pexels.com/photos/7254512/pexels-photo-7254512.jpeg" />
      <div class="card-product-infos">
        <h2><%= poisson.name %></h2>
        <p><%= poisson.category %></p>
        <p><%= poisson.price %></p>
      </div>
    </div>
    <!-- index.html.erb -->
    <%= link_to 'View Poisson', poisson_path(poisson) %>
  <% end %>
</ul>

app/views/poissons/_form.html.erb
<div class= "container">
  <div class= "row">

    <%= simple_form_for(@poisson) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :banner_url %>
        <%= form.input :image, as: :file, label: "Image du poisson" %>
      </div>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>

  </div>
</div>

app/views/poissons/index.html.erb
<div class="container mt-3">

<div class="row justify-content-center d-flex">
  <div class="col-md-8 col-sm-10 my-3">
    <%= form_with url: poissons_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control mr-2 mb-2 mb-sm-0",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Recherche", name: "", class: "btn" %>
    <% end %>
  </div>
</div>

  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.natgeofe.com/n/18708334-6fce-40b5-ade6-a7e2db7035f2/01-goldfish-nationalgeographic_1567132.jpg);">
    <div class="container">
      <h1 class="home-h1">Découvre nos <strong><%= Poisson.count %></strong> fabuleux poissons à louer !</h1>
    </div>
  </div>

  <div class="cards">
    <% @poissons.each do |poisson| %>
      <%= link_to poisson_path(poisson) do %>
        <div class="card grow" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(<%= poisson.picture_url %>)">
          <div class="card-infos">
            <h2 class="home-h2"><strong><%= poisson.name %></strong></h2>
            <p class="home-p">Votre <%= poisson.category %> pour seulement <strong><%= poisson.price %>€</strong> par jour !</p>
          </div>
        </div>
      <% end %>
    <% end %>

        <div style d-flex="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

  </div>
</div>

app/views/poissons/new.html.erb
<div class= "new">
  <div class= "form-container">
    <div class="form-inputs ">
      <%= simple_form_for(@poisson) do |f| %>
        <%= f.input :name %>
        <%= f.input :category %>
        <%= f.input :price %>
        <%= f.submit class: "btn" %>
      <% end %>


          <div style d-flex="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

    </div>

  </div>
</div>

app/views/poissons/profil.html.erb
<div class="container mt-3">
  <h1>Tous vos poissons !</h1>
    <div class="cards">
      <% @poissons.each do |poisson| %>
        <div class="card grow" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(<%= poisson.picture_url %>)">
          <div class="card-infos">
            <h2><strong><%= poisson.name %></strong></h2>
            <p>Votre <%= poisson.category %> est actuellement proposé en location au prix de <strong><%= poisson.price %>€</strong> par jour !</p>
          </div>
        </div>
      <% end %>
      <%= link_to poissons_new_path do %>
        <div class="card grow" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5))">
        <div class="card-infos">
        <h2><strong>Ajouter un nouveau poisson !</strong></h2>
        <p>Let's go !</p>
        </div>
      <% end %>
    </div>
    </div>
</div>

app/views/poissons/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="fish booking col-7 p-5">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(<%= @poisson.picture_url %>)">
        <div class="card-infos">
          <h2><strong><%= @poisson.name %></strong></h2>
          <p><%= @poisson.category %></p>
        </div>
      </div>
      <div class="card-description">
        <p><%= @poisson.description %></p>
        <p><strong>Propriétaire du poisson : <%= @poisson.user.prenom %></strong></p>
      </div>
    </div>
    <div class="col-1 p-5">
      <div>
      </div>
    </div>
    <div class="fish booking col-4 p-5">
      <h1>Réservez moi !</h1>
      <%= render 'locations/form', poisson: @poisson, location: @location %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    fishbnb made with <i class="fas fa-heart"></i> by Weeding Success Team
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://www.creativefabrica.com/wp-content/uploads/2020/09/09/Fish-Logo-Graphics-5365128-1-1-580x386.jpg", alt: "Logo" %>
      <span class="nav-item brand-name">
        fishbnb
      </span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Poissons disponibles🐡", poissons_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profil", profil_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://assets.mycast.io/actor_images/actor-beyonce-knowles-15034_large.jpg?1578032606", class: "avatar nav-link dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><%= link_to "Deconnexion", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link"  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>